language: ruby

sudo: false

bundler_args: --without development

before_install:
  - gem update --system
  - gem update bundler

rvm:
  - 2.5.1
  - ruby-head
  - jruby-9.1.16.0

gemfile:
  - Gemfile
  - gemfiles/driver_master.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby-9.1.16.0
      gemfile: gemfiles/driver_master.gemfile

env:
  global:
    - CI="travis"
    - JRUBY_OPTS="--server -J-Xms512m -J-Xmx1G"
  matrix:
    - MONGODB=2.6.12
    - MONGODB=3.4.10
    - MONGODB=3.6.2

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#mongoid"
